apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-system-sealed-secrets
  annotations:
    # argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: public-infra
  source:
    repoURL: https://github.com/SBK-DEMOS/GitOps-ArgoCD.git
    targetRevision: HEAD
    path: east/crossplane-system/crds/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # Sync policy
  syncPolicy:
    automated: {}
