apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: <replace encrypted data>
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system
    type: Opaque
