apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SBK-DEMOS/GitOps-ArgoCD.git
    targetRevision: HEAD
    path: 1.AutoDeploy/child-apps
  destination:
    server: https://kubernetes.default.svc  
    namespace: argoapps  

  syncPolicy:
    syncOptions: 
    - CreateNamespace=true  
    automated:
      selfHeal: true  
      prune: true  
