apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ns-crossplane-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: public-infra
  source:
    repoURL: https://github.com/SBK-DEMOS/GitOps-ArgoCD.git
    targetRevision: HEAD
    path: east/crossplane-system
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # Sync policy
  syncPolicy:
    automated: {}
