apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
   # argocd.argoproj.io/sync-wave: "-11"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: public-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.15.2
      helm:
        valueFiles:
          - $values/east1/kube-system/helmreleases/values/hr-sealed-secrets-values.yaml
    - repoURL: https://github.com/SBK-DEMOS/GitOps-ArgoCD.git
      targetRevision: HEAD
      ref: values
  # Sync policy
  syncPolicy:
    automated: {}
