apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-system-helmreleases
spec:
  project: public-infra
  source:
    repoURL: https://github.com/SBK_DEMOS/GitOps-ArgoCD.git
    targetRevision: HEAD
    path: east1/crossplane-system/helmreleases
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # Sync policy
  syncPolicy:
    automated: {}
